# Generated by Django 5.0.4 on 2024-04-26 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.CharField(max_length=255)),
                ("result", models.TextField()),
                (
                    "execution_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_valid", models.BooleanField(default=False)),
            ],
        ),
    ]
